### ISSUE TITLE
실록 데이터 스키마 구조 변화

### ISSUE THREAD

**Issue by drive0822** [drive0822/Silok-with-Deep-Learning#1]
각 실록은 explode 된 뒤 라벨링되어 다시 WarppedArray 형태로 변환 예정이다.
지금 바로 계층형 구조를 설계할 필요가 있는가?

**Comment by inspark9** [comment]
향후 문단 단위로 라벨링 작업을 하는 경우라던지, 혹은 라벨링 된 데이터를 기반으로 학습하는 과정을 고려해보면 지금 바로 계층형 구조가 필요한 시점은 아니라고 생각됩니다.

**Comment by drive0822** [comment]
본문은 구분자 '\n'으로 이루어진 스트링으로 저장하고 라벨은 차후 같이 묶어서 저장하는걸로 결정하고
이슈를 닫습니다.
